import type { Metadata } from 'next';
import Link from 'next/link';

export const metadata: Metadata = {
  title: 'Terms of Service — Non-Toxic Living',
  description: 'Terms of Service for the Non-Toxic Living app.',
};

function Header() {
  return (
    <header className="border-b border-[--site-border] bg-[--site-surface]">
      <div className="mx-auto flex max-w-5xl items-center justify-between px-6 py-4">
        <Link href="/" className="flex items-center gap-2.5">
          <div className="flex h-8 w-8 items-center justify-center rounded-lg bg-[--oxygen] text-white font-bold text-xs">
            NTL
          </div>
          <span className="text-base font-bold text-[--site-text]">Non-Toxic Living</span>
        </Link>
        <nav className="flex items-center gap-5 text-sm">
          <Link href="/support" className="text-[--site-text-secondary] hover:text-[--site-text] transition-colors">
            Support
          </Link>
          <Link href="/privacy" className="text-[--site-text-secondary] hover:text-[--site-text] transition-colors">
            Privacy
          </Link>
          <Link href="/terms" className="font-medium text-[--site-text]">
            Terms
          </Link>
        </nav>
      </div>
    </header>
  );
}

function Footer() {
  return (
    <footer className="border-t border-[--site-border] bg-[--site-surface] py-8 px-6">
      <div className="mx-auto flex max-w-5xl flex-col items-center gap-4 text-sm text-[--site-text-muted] sm:flex-row sm:justify-between">
        <span>&copy; {new Date().getFullYear()} Non-Toxic Living. All rights reserved.</span>
        <div className="flex gap-6">
          <Link href="/support" className="hover:text-[--site-text] transition-colors">Support</Link>
          <Link href="/privacy" className="hover:text-[--site-text] transition-colors">Privacy</Link>
          <Link href="/terms" className="hover:text-[--site-text] transition-colors">Terms</Link>
        </div>
      </div>
    </footer>
  );
}

export default function TermsPage() {
  return (
    <div
      className="min-h-screen font-[family-name:var(--font-space-grotesk)]"
      style={
        {
          background: 'var(--color-site-bg)',
          color: 'var(--color-site-text)',
          '--site-border': 'var(--color-site-border)',
          '--site-surface': 'var(--color-site-surface)',
          '--site-text': 'var(--color-site-text)',
          '--site-text-secondary': 'var(--color-site-text-secondary)',
          '--site-text-muted': 'var(--color-site-text-muted)',
          '--oxygen': 'var(--color-oxygen)',
        } as React.CSSProperties
      }
    >
      <Header />

      <main className="py-20 px-6">
        <div className="mx-auto max-w-3xl">
          <h1 className="text-3xl font-bold">Terms of Service</h1>
          <p className="mt-2 text-sm text-[--site-text-muted]">Last updated: February 9, 2026</p>

          <div className="mt-12 space-y-10 text-[--site-text-secondary] leading-relaxed">
            <section>
              <h2 className="text-lg font-bold text-[--site-text]">1. Acceptance of Terms</h2>
              <p className="mt-3">
                By downloading, installing, or using Non-Toxic Living (&quot;the app&quot;), you agree to be
                bound by these Terms of Service. If you do not agree, do not use the app.
              </p>
            </section>

            <section>
              <h2 className="text-lg font-bold text-[--site-text]">2. Description of Service</h2>
              <p className="mt-3">
                Non-Toxic Living is a mobile application that helps users identify potentially harmful
                ingredients in consumer products by scanning ingredient labels and providing AI-powered
                safety analysis. The app provides safety scores, ingredient breakdowns, and alternative
                product recommendations.
              </p>
            </section>

            <section>
              <h2 className="text-lg font-bold text-[--site-text]">3. Disclaimer of Medical Advice</h2>
              <p className="mt-3">
                The information provided by Non-Toxic Living is for informational purposes only and
                should not be considered medical advice, health advice, or a substitute for professional
                consultation. Safety scores and ingredient analyses are generated by AI and may not
                reflect all known risks. Always consult a qualified healthcare professional for health
                decisions, and check with a physician before making changes based on ingredient concerns,
                especially if you have allergies, sensitivities, or medical conditions.
              </p>
            </section>

            <section>
              <h2 className="text-lg font-bold text-[--site-text]">4. User Accounts</h2>
              <p className="mt-3">
                You may need to create an account to use certain features. You are responsible for
                maintaining the confidentiality of your login credentials and for all activity under
                your account. You agree to provide accurate information and notify us promptly of any
                unauthorized use.
              </p>
            </section>

            <section>
              <h2 className="text-lg font-bold text-[--site-text]">5. Subscriptions and Payments</h2>
              <ul className="mt-3 list-disc space-y-2 pl-6">
                <li>
                  Non-Toxic Living offers free and paid subscription tiers (Pro and Power).
                </li>
                <li>
                  Subscriptions are billed through the Apple App Store or Google Play Store.
                  Payment terms, renewal, and cancellation are governed by the respective store&apos;s policies.
                </li>
                <li>
                  Subscriptions automatically renew unless cancelled at least 24 hours before the end
                  of the current billing period.
                </li>
                <li>
                  You can manage or cancel your subscription through your device&apos;s subscription settings.
                </li>
                <li>
                  We reserve the right to change pricing with reasonable notice. Existing subscriptions
                  will not be affected until the next renewal period.
                </li>
              </ul>
            </section>

            <section>
              <h2 className="text-lg font-bold text-[--site-text]">6. Acceptable Use</h2>
              <p className="mt-3">You agree not to:</p>
              <ul className="mt-3 list-disc space-y-2 pl-6">
                <li>Use the app for any unlawful purpose.</li>
                <li>Attempt to reverse-engineer, decompile, or otherwise extract the source code of the app.</li>
                <li>Use automated tools to scrape, harvest, or extract data from the service.</li>
                <li>Circumvent or attempt to circumvent scan quotas or other usage limits.</li>
                <li>Share your account credentials with others or resell access to the service.</li>
              </ul>
            </section>

            <section>
              <h2 className="text-lg font-bold text-[--site-text]">7. Intellectual Property</h2>
              <p className="mt-3">
                All content, features, and functionality of Non-Toxic Living — including but not
                limited to text, graphics, logos, icons, algorithms, and software — are owned by
                Non-Toxic Living and are protected by copyright, trademark, and other intellectual
                property laws. You may not copy, modify, distribute, or create derivative works
                without our prior written consent.
              </p>
            </section>

            <section>
              <h2 className="text-lg font-bold text-[--site-text]">8. Accuracy of Information</h2>
              <p className="mt-3">
                While we strive to provide accurate ingredient analysis, we do not guarantee the
                completeness, accuracy, or reliability of any safety scores, ingredient data, or
                product recommendations. Product formulations may change, and our database may not
                reflect the most current information. Always verify ingredient information with the
                product manufacturer when in doubt.
              </p>
            </section>

            <section>
              <h2 className="text-lg font-bold text-[--site-text]">9. Limitation of Liability</h2>
              <p className="mt-3">
                To the maximum extent permitted by law, Non-Toxic Living and its affiliates shall not
                be liable for any indirect, incidental, special, consequential, or punitive damages,
                including but not limited to loss of profits, data, or goodwill, arising from your use
                of the app or reliance on any information provided by the app. Our total liability for
                any claim shall not exceed the amount you paid for the service in the 12 months
                preceding the claim.
              </p>
            </section>

            <section>
              <h2 className="text-lg font-bold text-[--site-text]">10. Product Recommendations</h2>
              <p className="mt-3">
                The app may suggest alternative products. Some recommendations may include affiliate
                links, meaning we may earn a commission if you make a purchase. This does not affect
                the price you pay. Recommendations are based on ingredient analysis and are not
                endorsements. We are not responsible for third-party products or their ingredients.
              </p>
            </section>

            <section>
              <h2 className="text-lg font-bold text-[--site-text]">11. Termination</h2>
              <p className="mt-3">
                We may suspend or terminate your access to the app at any time, with or without
                cause, with or without notice. Upon termination, your right to use the app ceases
                immediately. Sections that by their nature should survive termination will survive.
              </p>
            </section>

            <section>
              <h2 className="text-lg font-bold text-[--site-text]">12. Changes to Terms</h2>
              <p className="mt-3">
                We may update these terms from time to time. We will notify you of material changes
                by posting the updated terms on this page and updating the &quot;Last updated&quot; date.
                Continued use of the app after changes constitutes acceptance of the new terms.
              </p>
            </section>

            <section>
              <h2 className="text-lg font-bold text-[--site-text]">13. Contact</h2>
              <p className="mt-3">
                If you have questions about these terms, contact us at{' '}
                <a href="mailto:ntl@abrdn.co" style={{ color: 'var(--color-oxygen)' }} className="underline">
                  ntl@abrdn.co
                </a>.
              </p>
            </section>
          </div>
        </div>
      </main>

      <Footer />
    </div>
  );
}
